### ISSUE TITLE
Data Submitted Live?

### ISSUE THREAD

**Issue by michacassola** [maxitromer/wootic#1]
Hi Maxi, thanks for your plugin!

When a customer fills out the checkout form, will what they fill in be recorded live so one can do abandoned cart emails with mautic?

**Comment by maxitromer** [comment]
Hi Micha!

Wootic send data to mautic only when the 'Place Order' button is clicked.

Or for been more specific, every time the order change their status.

But ... you can use this amaizing plugin for what you need:

https://wordpress.org/plugins/woo-cart-abandonment-recovery/

With it you can config a webhook to send the abandoned cart data to your Mautic instance if the user don't complete their order.

Hope this help.
