### ISSUE TITLE
Issues with API - Data not being sent

### ISSUE THREAD

**Issue by tiagorodriguesdev** [maxitromer/wootic#2]
Hi @maxitromer 

First of all thanks for this repo that you've created, nice job. Most plugins are completely obsoletes or are really expensive delivering almost nothing.

To the issue:

**Environments**

Woocommerce 3.8.1 - WordPress 5.3.2 (Both Latest)

-  PHP 7.3
- MariaDB
- 8GB RAM
- 4 Cores VPS

Mautic (Latest)

- PHP 7.1
- MariaDB
- Same VPS specs.
- Cross-scripting disable.

Details:
- Using API

If the user place an order it will not be sent to Mautic automaticaly via API, but if I change the order status to **processing** automaticaly and then go back to **complete** it sends correctly all data (on complete status)

It looks like it's not catching the "Place Order".

I won't try the Form (even knowing it will work) because it'll be a very "handmade" job.

I'll be available soon to check your project from zero and make some improvements, what do you think? I'll be glad to help.

That's all for now.

Thanks

**Comment by maxitromer** [comment]
Hi Tiago, 

Thanks for been here and sorry for the delay in my answer.

> Most plugins are completely obsoletes or are really expensive delivering almost nothing.

I'm with you here, I find exactly the same a couple of months ago and I hope this plugin can help.

About your issue:

> If the user place an order it will not be sent to Mautic automaticaly via API, but if I change the order status to processing automaticaly and then go back to complete it sends correctly all data (on complete status)

I was testing and can't relate in my dev enviroment.

The plugin use the `woocommerce_order_status_changed` hook that fires when and order is changed including the creation and deletion.

Please can you share your Mautic and PHP error logs if any?

> I'll be available soon to check your project from zero and make some improvements, what do you think? I'll be glad to help.

Perfect! I'm in and here to help in what you need.

**Comment by maxitromer** [comment]
@TiagoRodrigues what Payment Processor are you using?

I'm making some tests and I'm experiencing the same situation with Mercado Pago and I think this is not related to the plugin but to the way Mercado Pago process the payments.

I'll be here waiting for your answer.

**Comment by tiagorodriguesdev** [comment]
Hi @maxitromer sorry about the delay.
I’ve found that the bug was that your first commit was setting API for your own test. Please change your password if it is a production instance.

As soon as I found (couple days later when I started looking the code) I’ve changed on my website and it started sending correctly via API to my Mautic all my transactions.

I can see it’s updated, so I’d like to know if it’s running smoothly now. I’m able to test if you say so. 

We need to think about subscriptions too...to add an specific tag in case the product is a subscription.

I’m a little bit overwhelmed right now but I’m REALLY following your job and I’ll help asap.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maxitromer** [comment]
Thanks for the feedback @TiagoRodrigues and dont worry about the password, I'm developing locally.

Yes it's updated and working fine from my side.

About subscriptions it's posible to use the `product_type` field for that.

> I’m a little bit overwhelmed right now but I’m REALLY following your job and I’ll help asap.
 
Don't worry, the plugin is working and we have time to improve.

If you have some ideas please add it as new issues to talk there and clearly define a path and go for it.

**Comment by TiagoRodrigues** [comment]
Solved.
