### ISSUE TITLE
3rd part of the product SKU format

### ISSUE THREAD

**Issue by KitKatCarson** [maxitromer/wootic#4]
When setting the required product SKU, you mention there are 3 parts divided by _
I understand the first part, and second, but is the 3rd part  "_PT15" any different than the second part, action form codes?

Does PT represent an action form code and 15 another mautic form number, like CO87 does?

Thank you!

**Comment by maxitromer** [comment]
Hi @KitKatCarson 

Sorry I missed that info in the readme, now is added.

The 3rd part (`PT15` in the readme example) could be used for the number SKU itself with your product information ( `JEAN-235544` ) or could be blank if you dont use SKU for your products.

> Does PT represent an action form code and 15 another mautic form number, like CO87 does?

No, in my case I'm using it with another custom plugin not related, thats why the `PT15` there.

Hope that clarify and help.
