### ISSUE TITLE
First Name, Last Name and Addresses not being sent using form option in wootic

### ISSUE THREAD

**Issue by EmprendoHub** [maxitromer/wootic#5]
Hi there, first of all just wanted to say thank you so much for creating this plugin it's amazing! 

Just wanted to get some help troubleshooting and issue I'm having. 

Issue: Wwootic is not sending over the first name, last name and addresses Fields.

All other fields are being populated and the contact is created in Mautic side. 

Also worth mentioning I tested the form filling in the fields manually on Mautic side and everything is working fine.

I'm using Woocommerce Versión 4.0.1 

This is My Wootic Config:
![Wootic Config Screen Capture](https://user-images.githubusercontent.com/54673042/77553109-ffcdd880-6e79-11ea-8e10-dce466b1feb0.png)

I hope i provided enough info on the issue, if not let me know what else I can provide on my end to explain in a bit better.

Thanks in advance for all the help.

**Comment by maxitromer** [comment]
Hi @EmprendoHub !

I can see you are using forms for this integration.

Please check that your form fields have this field values in the label:

- firstname
- lastname

Something like this:

![screenshot_2020-03-31_00-10-03](https://user-images.githubusercontent.com/6311835/77983005-29f12180-72e4-11ea-87c2-824825c6b922.png)

Hope this solve your problem.
