### ISSUE TITLE
CONTACTS NOT PUT ON A SEGMENT LIST ISSUE

### ISSUE THREAD

**Issue by dewalemichael** [maxitromer/wootic#6]
Hello @maxitromer,

How have you been, I believe you are safe and doing okay?

I have an issue with wootic at the moment...

Once contact complete a transaction and gets tracked with wootic tags, unfortunately, they don't get added to a segment they should be in Mautic. [They are identified in mautic but they are not put on a segment]

Please any idea what's going on?

Please see the references
https://www.screencast.com/t/dtaYcEQJwpy8

![Wootic](https://user-images.githubusercontent.com/51846239/77813714-04c59e80-70ab-11ea-9003-0271eae52f62.jpg)

![Screenshot of WooCommerce settings ‹ Beauty Marketing Online — WordPress](https://user-images.githubusercontent.com/51846239/77813776-87e6f480-70ab-11ea-9c3c-5a55a244a70b.jpg)

**Comment by maxitromer** [comment]
Hi @dewalemichael !

I'm fine, thanks for ask!

All you have to do is to create a filter in your segment and add your tag:

![screenshot_2020-03-30_23-58-50](https://user-images.githubusercontent.com/6311835/77982345-7f2c3380-72e2-11ea-9e70-34bdced17c02.png)

Hope this help.
